# Generated by Django 5.2.4 on 2025-07-04 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('PRO', 'En Progreso'), ('COM', 'Completada')], default='PEN', max_length=3)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
